included:
  - .

excluded:
  - Pods
  - MBUITest

# Включаем анализаторные правила
analyzer_rules:
  - unused_import
  - unused_declaration

disabled_rules:
  - trailing_whitespace
  - identifier_name
  - force_cast

line_length:
  warning: 150
  error: 180

file_length:
  warning: 500
  error: 600

type_body_length:
  warning: 400
  error: 500

function_body_length:
  warning: 100
  error: 150

function_parameter_count:
  warning: 10
  error: 15

opt_in_rules:
  - unneeded_override
  - explicit_init
  - closure_spacing
  - multiline_parameters_brackets
  - attributes
